Repository googleinterns/step125-2020, pull requests merged in 2020-07, with the labels that each got.

#26 Delete extra pom.xml
  pom.xml
Labels: house keeping

#27 Create maven.yml
  .github/workflows/maven.yml
Labels: cla: yes

#31 Updates to webform to prevent reloading the page when clicking submit.
  maptivist/src/main/webapp/index.html
Labels: cla: yes

#29 Created the marker servlet and test for functions
  maptivist/src/main/java/com/google/sps/Marker.java
  maptivist/src/main/java/com/google/sps/servlets/MarkerServlet.java
  maptivist/src/test/java/com/google/sps/MarkerServletFunctionTest.java
  maptivist/src/test/java/com/google/sps/MarkerTest.java
Labels: cla: yes

#30 Display map and markers
  maptivist/pom.xml
  maptivist/src/main/webapp/index.html
  maptivist/src/main/webapp/script.js
  maptivist/src/main/webapp/style.css
Labels: bug, cla: yes

#40 AA marker servlet
  maptivist/src/main/java/com/google/sps/servlets/MarkerServlet.java
  maptivist/src/main/webapp/index.html
  maptivist/src/test/java/com/google/sps/MarkerServletFunctionTest.java
Labels: cla: yes

#41 Add category id in form and infowindow
  maptivist/src/main/java/com/google/sps/servlets/MarkerServlet.java
  maptivist/src/main/webapp/index.html
  maptivist/src/main/webapp/script.js
Labels: cla: yes, enhancement

#44 Js filter by boundary
  maptivist/pom.xml
  maptivist/src/main/java/com/google/sps/Marker.java
  maptivist/src/main/java/com/google/sps/servlets/MarkerServlet.java
  maptivist/src/main/webapp/filter.js
  maptivist/src/main/webapp/index.html
  maptivist/src/main/webapp/script.js
  maptivist/src/test/java/com/google/sps/MarkerServletFunctionTest.java
  maptivist/src/test/java/com/google/sps/MarkerTest.java
  package-lock.json
  package.json
Labels: cla: yes

#47 Address form input
  maptivist/src/main/java/com/google/sps/Marker.java
  maptivist/src/main/java/com/google/sps/servlets/MarkerServlet.java
  maptivist/src/main/webapp/index.html
  maptivist/src/main/webapp/script.js
  maptivist/src/main/webapp/style.css
  maptivist/src/test/java/com/google/sps/MarkerServletFunctionTest.java
  maptivist/src/test/java/com/google/sps/MarkerTest.java
Labels: cla: yes, enhancement

#51 Update Marker.java
  maptivist/src/main/java/com/google/sps/Marker.java
Labels: cla: yes

#48 Fire base single page
  maptivist/src/main/webapp/index.html
  maptivist/src/main/webapp/script.js
  maptivist/src/main/webapp/style.css
Labels: cla: yes

#52 Debug markers
  maptivist/src/main/java/com/google/sps/Marker.java
  maptivist/src/main/java/com/google/sps/servlets/MarkerServlet.java
  maptivist/src/main/java/com/google/sps/servlets/VoteServlet.java
  maptivist/src/main/webapp/index.html
  maptivist/src/main/webapp/script.js
Labels: cla: yes, enhancement, house keeping

#55 AA marker dates
  maptivist/src/main/java/com/google/sps/Marker.java
  maptivist/src/main/java/com/google/sps/servlets/MarkerServlet.java
  maptivist/src/main/java/com/google/sps/servlets/VoteServlet.java
  maptivist/src/main/webapp/index.html
  maptivist/src/main/webapp/script.js
  maptivist/src/main/webapp/style.css
  maptivist/src/test/java/com/google/sps/MarkerServletFunctionTest.java
  maptivist/src/test/java/com/google/sps/MarkerTest.java
Labels: cla: yes

#58 Update script.js
  maptivist/src/main/webapp/script.js
Labels: cla: yes

#59 AA fix marker display
  maptivist/src/main/java/com/google/sps/servlets/MarkerServlet.java
  maptivist/src/main/webapp/index.html
  maptivist/src/main/webapp/script.js
Labels: bug, cla: yes
